//export const HOST = "http://127.0.0.1:5500";
export const HOST = 'http://localhost:4200'
export const SIGN_IN = 'Sign in';
export const SIGN_UP = 'Sign up';
export const CONFIRM = 'Confirm';
export const SIGN_OUT = 'Sign out';
export const USERNAME = 'Username';
export const PASSWORD = 'Password';
export const NAME = 'Name';
export const REPEAT_PASSWORD = 'Repeat Password';
